services: 
    db: 
      image: postgres:latest
      container_name: my_db_mongkhon
      environment: 
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
      ports: 
        - "${DATABASE_PORT}:5432"